export const PROBLEM_LIST = [
  'Pandemi Covid-19',
  'Pembelajaran Jarak Jauh',
  'Kekerasan terhadap anak dan perempuan',
  'Kesehatan Mental',
  'Lingkungan dan kelestarian alam',
  'Lapangan pekerjaan',
  'Korupsi',
  'Kemacetan',
  'Banjir',
  'Penegakan hukum',
  'Narkoba',
  'Perundungan/bullying/cyber-bullying',
  'Hoax dan literasi digital',
  'Minat baca dan tingkat literasi anak dan remaja',
  'Toleransi',
  'Perkelahian antar remaja',
  'Nasionalisme',
  'Disabilitas',
  'Pernikahan dini',
  'Kesehatan reproduksi',
  'Lainnya',
];
