export const ACCOUNT_TYPE = ['siswa', 'mentor', 'guru', 'supporter'];

export const LIST_FORM = {
  siswa: [
    {
      key: 'schoolDegree',
      as: 'dropdown',
      label: 'Jenjang',
      required: true,
      columns: '6',
    },
    {
      key: 'typeSchool',
      as: 'dropdown',
      label: 'Tipe',
      required: true,
      columns: '6',
    },
    {
      key: 'grade',
      as: 'dropdown',
      label: 'Kelas',
      required: true,
      columns: '12',
    },
    {
      key: 'province',
      as: 'dropdown',
      label: 'Provinsi',
      required: true,
      columns: '6',
    },
    {
      key: 'city',
      as: 'dropdown',
      label: 'Kota/Kabupaten',
      required: true,
      columns: '6',
    },
    {
      key: 'schoolName',
      as: 'textfield',
      label: 'Nama Instansi Pendidikan',
      required: true,
      columns: '12',
    },
  ],
  guru: [
    {
      key: 'schoolDegree',
      as: 'dropdown',
      label: 'Jenjang',
      required: true,
      columns: '6',
    },
    {
      key: 'typeSchool',
      as: 'dropdown',
      label: 'Tipe',
      required: true,
      columns: '6',
    },
    {
      key: 'province',
      as: 'dropdown',
      label: 'Provinsi',
      required: true,
      columns: '6',
    },
    {
      key: 'city',
      as: 'dropdown',
      label: 'Kota/Kabupaten',
      required: true,
      columns: '6',
    },
    {
      key: 'schoolName',
      as: 'textfield',
      label: 'Nama Instansi Pendidikan',
      required: true,
      columns: '12',
    },
    {
      key: 'subject',
      as: 'textfield',
      label: 'Mata Pelajaran yang diajarkan',
      required: true,
      columns: '12',
    },
    {
      key: 'position',
      as: 'textfield',
      label: 'Jabatan',
      required: true,
      columns: '12',
    },
    {
      key: 'degree',
      as: 'textfield',
      label: 'Jenjang pendidikan terakhir',
      required: true,
      columns: '12',
    },
    {
      key: 'yearOfExperience',
      as: 'dropdown',
      label: 'Sudah mengajar sejak tahun',
      required: true,
      columns: '12',
    },
  ],
  mentor: [
    {
      key: 'position',
      as: 'textfield',
      label: 'Jabatan',
      required: true,
      columns: '12',
    },
    {
      key: 'organization',
      as: 'textfield',
      label: 'Nama Organisasi/Perusahaan tempat bekerja saat ini',
      required: true,
      columns: '12',
    },
    {
      key: 'degree',
      as: 'dropdown',
      label: 'Jenjang pendidikan terakhir',
      required: true,
      columns: '12',
    },
    {
      key: 'subject',
      as: 'textfield',
      label: 'Bidang keahlian yang bisa diajarkan',
      required: true,
      columns: '12',
    },
  ],
  supporter: [
    {
      key: 'positoin',
      as: 'textfield',
      label: 'Jabatan Pekerjaan',
      required: true,
      columns: '12',
    },
    {
      key: 'organization',
      as: 'textfield',
      label: 'Nama Organisasi/Perusahaan tempat bekerja saat ini',
      required: true,
      columns: '12',
    },
    {
      key: 'speciality',
      as: 'textfield',
      label: 'Bidang keahlian',
      required: true,
      columns: '12',
    },
    {
      key: 'degree',
      as: 'dropdown',
      label: 'Jenjang pendidikan terakhir',
      required: true,
      columns: '12',
    },
  ],
};
